# Generated by Django 5.2.4 on 2025-08-07 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={'verbose_name': 'Appareil de confiance', 'verbose_name_plural': 'Appareils de confiance'},
        ),
        migrations.RenameField(
            model_name='trusteddevice',
            old_name='last_used_at',
            new_name='last_used',
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='location',
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
