# Generated by Django 5.2.4 on 2025-08-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_trusteddevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={},
        ),
        migrations.RenameField(
            model_name='trusteddevice',
            old_name='last_used',
            new_name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
