# Generated by Django 5.2.4 on 2025-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
