# Generated by Django 5.2.4 on 2025-08-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_trusteddevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
