# Generated by Django 5.2.4 on 2025-07-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
