# Generated by Django 5.2.4 on 2025-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_trusteddevice_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
