# Generated by Django 5.2.4 on 2025-08-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_trusteddevice_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='browser_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='device_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='os_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
