# Generated by Django 5.2.4 on 2025-07-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_oldprofilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('scheduled_deletion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='profile_picture_change', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_deletion'], name='users_pendi_schedul_c128b3_idx')],
            },
        ),
        migrations.DeleteModel(
            name='OldProfilePhoto',
        ),
    ]
