# Generated by Django 5.2.4 on 2025-07-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pendingfiledeletion_delete_oldprofilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingfiledeletion',
            name='trash_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
