# Generated by Django 5.2.4 on 2025-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
