# Generated by Django 5.2.4 on 2025-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pendingfiledeletion_trash_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofa_totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
