# Generated by Django 5.2.4 on 2025-08-31 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('follow', 'Follow'), ('close_friend', 'Close Friend')], default='follow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['from_user', 'relationship_type'], name='users_userr_from_us_b70767_idx'), models.Index(fields=['to_user', 'relationship_type'], name='users_userr_to_user_c46ace_idx'), models.Index(fields=['created_at'], name='users_userr_created_f33ba1_idx')],
                'unique_together': {('from_user', 'to_user', 'relationship_type')},
            },
        ),
    ]
