# Generated by Django 5.2.4 on 2025-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='last_shown',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='show_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'position'], name='users_userr_user_id_58537e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['last_shown'], name='users_userr_last_sh_756063_idx'),
        ),
    ]
