# Generated by Django 5.2.4 on 2025-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userrecommendation_last_shown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendation',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'score'], name='users_userr_user_id_a7b825_idx'),
        ),
    ]
