# Generated by Django 5.2.4 on 2025-08-18 17:27

import django.db.models.deletion
import photos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('original_file', models.ImageField(max_length=500, upload_to=photos.models.photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=photos.models.thumbnail_upload_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_extension', models.CharField(max_length=10)),
                ('is_raw', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('lens_make', models.CharField(blank=True, max_length=100)),
                ('lens_model', models.CharField(blank=True, max_length=100)),
                ('focal_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('focal_length_35mm', models.PositiveIntegerField(blank=True, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=50)),
                ('aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('exposure_bias', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('exposure_mode', models.CharField(blank=True, max_length=50)),
                ('metering_mode', models.CharField(blank=True, max_length=50)),
                ('white_balance', models.CharField(blank=True, max_length=50)),
                ('color_space', models.CharField(blank=True, max_length=50)),
                ('flash', models.CharField(blank=True, max_length=100)),
                ('digital_zoom_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('date_taken', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('software_used', models.CharField(blank=True, max_length=100)),
                ('copyright', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date_taken', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date_taken'], name='photos_phot_user_id_e963c4_idx'), models.Index(fields=['is_public', '-date_taken'], name='photos_phot_is_publ_acff55_idx'), models.Index(fields=['camera_make', 'camera_model'], name='photos_phot_camera__362392_idx'), models.Index(fields=['tags'], name='photos_phot_tags_ab9d0a_idx')],
            },
        ),
    ]
