# Generated by Django 5.2.4 on 2025-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
    ]
