# Generated by Django 5.2.4 on 2025-08-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('collection_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared'), ('group', 'Group')], default='personal', max_length=50)),
                ('sort_order', models.CharField(choices=[('date_desc', 'Newest First'), ('date_asc', 'Oldest First'), ('alphabetical_asc', 'A-Z'), ('alphabetical_desc', 'Z-A'), ('random', 'Random'), ('custom', 'Custom')], default='date_desc', max_length=20)),
                ('custom_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_collections', to=settings.AUTH_USER_MODEL)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_cover', to='photos.photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_photos', to='photos.collection')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_photos', to='photos.photo')),
            ],
            options={
                'verbose_name': 'Collection Photo',
                'verbose_name_plural': 'Collection Photos',
                'ordering': ['order', 'added_at'],
                'unique_together': {('collection', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(related_name='collections', through='photos.CollectionPhoto', to='photos.photo'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', '-updated_at'], name='photos_coll_owner_i_307cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-is_public', '-updated_at'], name='photos_coll_is_publ_f9b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['tags'], name='photos_coll_tags_7f997b_idx'),
        ),
    ]
