# Generated by Django 5.2.4 on 2025-08-22 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_collection_collectionphoto_collection_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='photos_coll_is_publ_f9b4e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photos_phot_is_publ_acff55_idx',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='is_public',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='is_public',
            new_name='is_private',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-is_private', '-updated_at'], name='photos_coll_is_priv_307931_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_private', '-date_taken'], name='photos_phot_is_priv_7aee85_idx'),
        ),
    ]
