# Generated by Django 5.2.4 on 2025-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_collection_photos_coll_is_publ_f9b4e7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dominant_colors',
            field=models.JSONField(blank=True, help_text='JSON data containing dominant colors analysis', null=True),
        ),
    ]
