# Generated by Django 5.2.4 on 2025-08-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_dominant_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dominant_colors',
        ),
    ]
