# Generated by Django 5.2.4 on 2025-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_remove_photo_dominant_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='colors_extracted',
            field=models.BooleanField(default=False, help_text='Whether dominant colors have been extracted'),
        ),
        migrations.AddField(
            model_name='photo',
            name='dominant_color_1',
            field=models.CharField(blank=True, help_text='Primary dominant color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='photo',
            name='dominant_color_2',
            field=models.CharField(blank=True, help_text='Secondary dominant color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='photo',
            name='dominant_color_3',
            field=models.CharField(blank=True, help_text='Tertiary dominant color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='photo',
            name='dominant_color_4',
            field=models.CharField(blank=True, help_text='Fourth dominant color in hex format', max_length=7),
        ),
        migrations.AddField(
            model_name='photo',
            name='dominant_color_5',
            field=models.CharField(blank=True, help_text='Fifth dominant color in hex format', max_length=7),
        ),
    ]
