# Generated by Django 5.2.4 on 2025-09-01 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_colors_extracted_photo_dominant_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Image embedding vector (512D) for similarity search', null=True, size=512),
        ),
    ]
