# Generated by Django 5.2.4 on 2025-09-01 20:42

from django.db import migrations, models
import django.contrib.postgres.fields


def convert_jsonb_to_array(apps, schema_editor):
    """Convert JSONB embedding data to ArrayField format"""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # First, create a temporary column
        cursor.execute("""
            ALTER TABLE photos_photo 
            ADD COLUMN embedding_temp double precision[512];
        """)
        
        # Convert JSONB data to array format
        cursor.execute("""
            UPDATE photos_photo 
            SET embedding_temp = (
                SELECT array_agg(value::double precision)
                FROM jsonb_array_elements_text(embedding)
            )
            WHERE embedding IS NOT NULL;
        """)
        
        # Drop the old column and rename the new one
        cursor.execute("ALTER TABLE photos_photo DROP COLUMN embedding;")
        cursor.execute("ALTER TABLE photos_photo RENAME COLUMN embedding_temp TO embedding;")


def reverse_convert_array_to_jsonb(apps, schema_editor):
    """Reverse conversion: ArrayField to JSONB"""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # Create temporary JSONB column
        cursor.execute("""
            ALTER TABLE photos_photo 
            ADD COLUMN embedding_temp jsonb;
        """)
        
        # Convert array data to JSONB format
        cursor.execute("""
            UPDATE photos_photo 
            SET embedding_temp = to_jsonb(embedding)
            WHERE embedding IS NOT NULL;
        """)
        
        # Drop the old column and rename the new one
        cursor.execute("ALTER TABLE photos_photo DROP COLUMN embedding;")
        cursor.execute("ALTER TABLE photos_photo RENAME COLUMN embedding_temp TO embedding;")


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_embedding'),
    ]

    operations = [
        migrations.RunPython(
            convert_jsonb_to_array,
            reverse_convert_array_to_jsonb,
        ),
        migrations.AlterField(
            model_name='photo',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), 
                size=512, 
                blank=True, 
                null=True, 
                help_text='Image embedding vector (512D) for similarity search'
            ),
        ),
    ]
