# Generated by Django 5.2.4 on 2025-09-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_convert_embedding_to_arrayfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_similarity', models.FloatField(help_text='Visual similarity (embeddings)')),
                ('exif_similarity', models.FloatField(help_text='EXIF similarity')),
                ('final_similarity', models.FloatField(help_text='Final hybrid similarity')),
                ('method', models.CharField(choices=[('cosine', 'Cosine Similarity'), ('pearson', 'Pearson Correlation')], default='cosine', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_photo1', to='photos.photo')),
                ('photo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_photo2', to='photos.photo')),
            ],
            options={
                'ordering': ['-final_similarity'],
                'indexes': [models.Index(fields=['photo1', 'method'], name='photos_phot_photo1__27722f_idx'), models.Index(fields=['photo2', 'method'], name='photos_phot_photo2__f95293_idx'), models.Index(fields=['final_similarity'], name='photos_phot_final_s_9384d9_idx')],
                'unique_together': {('photo1', 'photo2', 'method')},
            },
        ),
    ]
